# Generated by Django 5.1.4 on 2026-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_display_name_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(blank=True, choices=[('bald-beard', 'bald-beard'), ('quiff', 'quiff'), ('long-hair', 'long-hair'), ('dark-hair', 'dark-hair'), ('bob', 'bob'), ('wavy-hair', 'wavy-hair')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
