# Generated by Django 5.1.4 on 2026-07-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presence_connections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
