# Generated by Django 5.1.4 on 2026-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
