# Generated by Django 5.1.4 on 2026-08-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_channel_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_dm',
            field=models.BooleanField(default=False),
        ),
    ]
